# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      runner_id:
        description:  please pass the runner which platform that you want to use
        required: true
jobs:
  demorun:
    runs-on: ${{ inputs.runner_id }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: demo-2
      - run: |
           date > date.txt
           git config user.name github-actions-in-place
           git config user.email github-actions-in-place@no-reply.com
           git add .
           git commit -m "date generated" .
           git push
           
      

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls -ltr 
          
