name: JAVA CI Pipeline
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
      - 'feature/*'
jobs:
  MavenBuild:
     runs-on: ubuntu-latest
     steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        
      - name: Code Build
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '11'
      -  run: |
            pwd && ls -ltr 
            mvn clean install 
            
      - name: Code Test
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '11'
      -  run: |
            pwd && ls -ltr 
            mvn test
            
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Build and analyze
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=github-action-pipeline-codequality
